### PR TITLE
Idiomatic startup enabling REPL

### PR DESCRIPTION
**Pull request by Mantrum**
Lets us import homunculus without starting the client

### CODE REVIEW

**Comment by Az4reus** [comment]
Why not just throw `client = discord.Client()`in the `main` function as well? 

Also, what's the `sys.exit()` for, given that its already the last instruction in the program? :3

**Comment by Mantrum** [comment]
You're right, might as well move that call as well.

`sys.exit()` is just there so we have control over what the program returns, if we ever want that. Might as well remove it for now if you prefer.

**Comment by Az4reus** [comment]
Nah I just genuinely didn't know about `sys.exit()`. Is it about the return
codes, ie, `$?`?

I don't mind it, just didn't know about it.

**Comment by Mantrum** [comment]
Ah, I remember why I had `client = discord.Client()` outside of `main()` now. It's required for the decorators in global space, and allows us to access the `client` object via REPL.

**Comment by Az4reus** [comment]
Right, I'll just merge it then.

**Pull request merged**
